/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandpahost;


import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;


/**
 *
 * @author Stephan Zapotocky / zactrack.com
 */
public class MidiWindow extends javax.swing.JFrame implements MouseListener
{

    /**
     * Creates new form MidiWindow
     */
    public MidiWindow()
    {
        initComponents();
        
        Artnet.Get(); //init Artnet
        
        for(int i = 0; i<30; i++)
        {
            ExecPanel panel = new ExecPanel(i);
            execScrollContent.add(panel);
            panel.setSize(20, panel.getHeight());
            panel.setPreferredSize(panel.getSize());
            
            if(i%5==4 && i<29)
            {
                JPanel sep = new JPanel();
                sep.setSize(30, panel.getHeight());
                execScrollContent.add(sep);
            }
                
        }
        
        buttonChannelPlus.addMouseListener(this);
        buttonChannelMinus.addMouseListener(this);
        buttonFaderPlus.addMouseListener(this);
        buttonFaderMinus.addMouseListener(this);
        buttonButtonPlus.addMouseListener(this);
        buttonButtonMinus.addMouseListener(this);
        
        add(new ProgrammerPanel());
        
        setTitle("GrandPA - GrandMA Powered By Arduino");
        this.setSize(1850, 400);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        buttonChannelPlus = new javax.swing.JButton();
        buttonChannelMinus = new javax.swing.JButton();
        buttonFaderPlus = new javax.swing.JButton();
        buttonFaderMinus = new javax.swing.JButton();
        buttonButtonPlus = new javax.swing.JButton();
        buttonButtonMinus = new javax.swing.JButton();
        execScrollPane = new javax.swing.JScrollPane();
        execScrollContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(93, 138));
        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 10, 10));

        buttonChannelPlus.setText("Ch Pg+");
        jPanel1.add(buttonChannelPlus);

        buttonChannelMinus.setText("Ch Pg-");
        jPanel1.add(buttonChannelMinus);

        buttonFaderPlus.setText("Fd Pg+");
        jPanel1.add(buttonFaderPlus);

        buttonFaderMinus.setText("Fd Pg-");
        jPanel1.add(buttonFaderMinus);

        buttonButtonPlus.setText("Bt Pg+");
        jPanel1.add(buttonButtonPlus);

        buttonButtonMinus.setText("Bt Pg-");
        jPanel1.add(buttonButtonMinus);

        getContentPane().add(jPanel1);

        execScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        execScrollPane.setPreferredSize(new java.awt.Dimension(1050, 480));

        execScrollContent.setPreferredSize(new java.awt.Dimension(1900, 300));
        execScrollContent.setLayout(new javax.swing.BoxLayout(execScrollContent, javax.swing.BoxLayout.LINE_AXIS));
        execScrollPane.setViewportView(execScrollContent);

        getContentPane().add(execScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonButtonMinus;
    private javax.swing.JButton buttonButtonPlus;
    private javax.swing.JButton buttonChannelMinus;
    private javax.swing.JButton buttonChannelPlus;
    private javax.swing.JButton buttonFaderMinus;
    private javax.swing.JButton buttonFaderPlus;
    private javax.swing.JPanel execScrollContent;
    private javax.swing.JScrollPane execScrollPane;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me)
    {
        
    }

    @Override
    public void mousePressed(MouseEvent me)
    {
        if(me.getSource().equals(buttonChannelPlus))
            Artnet.Get().sendArtnet(156, 255);
            //MIDI.sendNoteMessage((short)1, (short)86, (short)127, false);
        else if(me.getSource().equals(buttonChannelMinus))
            Artnet.Get().sendArtnet(155, 255);
            //MIDI.sendNoteMessage((short)1, (short)85, (short)127, false);
        else if(me.getSource().equals(buttonFaderPlus))
            Artnet.Get().sendArtnet(154, 255);
            //MIDI.sendNoteMessage((short)1, (short)84, (short)127, false);
        else if(me.getSource().equals(buttonFaderMinus))
            Artnet.Get().sendArtnet(153, 255);
            //MIDI.sendNoteMessage((short)1, (short)83, (short)127, false);
        else if(me.getSource().equals(buttonButtonPlus))
            Artnet.Get().sendArtnet(152, 255);
            //MIDI.sendNoteMessage((short)1, (short)82, (short)127, false);
        else if(me.getSource().equals(buttonButtonMinus))
            Artnet.Get().sendArtnet(151, 255);
            //MIDI.sendNoteMessage((short)1, (short)81, (short)127, false);
    }

    @Override
    public void mouseReleased(MouseEvent me)
    {
        if(me.getSource().equals(buttonChannelPlus))
            Artnet.Get().sendArtnet(156, 0);
            //MIDI.sendNoteMessage((short)1, (short)86, (short)127, true);
        else if(me.getSource().equals(buttonChannelMinus))
            Artnet.Get().sendArtnet(155, 0);
            //MIDI.sendNoteMessage((short)1, (short)85, (short)127, true);
        else if(me.getSource().equals(buttonFaderPlus))
            Artnet.Get().sendArtnet(154, 0);
            //MIDI.sendNoteMessage((short)1, (short)84, (short)127, true);
        else if(me.getSource().equals(buttonFaderMinus))
            Artnet.Get().sendArtnet(153, 0);
            //MIDI.sendNoteMessage((short)1, (short)83, (short)127, true);
        else if(me.getSource().equals(buttonButtonPlus))
            Artnet.Get().sendArtnet(152, 0);
            //MIDI.sendNoteMessage((short)1, (short)82, (short)127, true);
        else if(me.getSource().equals(buttonButtonMinus))
            Artnet.Get().sendArtnet(151, 0);
            //MIDI.sendNoteMessage((short)1, (short)81, (short)127, true);
    }

    @Override
    public void mouseEntered(MouseEvent me)
    {
        
    }

    @Override
    public void mouseExited(MouseEvent me)
    {
        
    }
}
