/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grandpahost;


import java.io.OutputStream;


/**
 *
 * @author Stephan Zapotocky / zactrack.com
 */
public class Window extends javax.swing.JFrame
{
    private OutputStream out;
    /**
     * Creates new form Window
     */
    public Window(OutputStream out)
    {
        initComponents();
        
        this.out = out;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        exec1Button = new javax.swing.JButton();
        exec3Button = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        encoder1PlusButton = new javax.swing.JButton();
        exec2Button = new javax.swing.JButton();
        encoder1MinusButton = new javax.swing.JButton();
        blackoutButton = new javax.swing.JButton();
        encoder2MinusButton = new javax.swing.JButton();
        encoder2PlusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exec1Button.setText("1");
        exec1Button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exec1ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                exec1ButtonMouseReleased(evt);
            }
        });

        exec3Button.setText("3");
        exec3Button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exec3ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                exec3ButtonMouseReleased(evt);
            }
        });

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSlider1StateChanged(evt);
            }
        });

        encoder1PlusButton.setText(">>");
        encoder1PlusButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                encoder1PlusButtonActionPerformed(evt);
            }
        });

        exec2Button.setText("2");
        exec2Button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exec2ButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                exec2ButtonMouseReleased(evt);
            }
        });

        encoder1MinusButton.setText("<<");
        encoder1MinusButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                encoder1MinusButtonActionPerformed(evt);
            }
        });

        blackoutButton.setText("B.O.");
        blackoutButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                blackoutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                blackoutButtonMouseReleased(evt);
            }
        });
        blackoutButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                blackoutButtonActionPerformed(evt);
            }
        });

        encoder2MinusButton.setText("<<");
        encoder2MinusButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                encoder2MinusButtonActionPerformed(evt);
            }
        });

        encoder2PlusButton.setText(">>");
        encoder2PlusButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                encoder2PlusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exec1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exec2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(168, 168, 168)
                .addComponent(encoder1MinusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encoder1PlusButton)
                .addGap(86, 86, 86)
                .addComponent(encoder2MinusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encoder2PlusButton)
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(exec3Button)
                    .addContainerGap(718, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(517, Short.MAX_VALUE)
                    .addComponent(blackoutButton)
                    .addGap(205, 205, 205)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(exec2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(encoder1PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encoder1MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encoder2PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encoder2MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147)))
                .addComponent(exec1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(exec3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(blackoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send(String command)
    {
        try
        {
            command += "\n";
            out.write(command.getBytes());
            out.flush();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSlider1StateChanged
    {//GEN-HEADEREND:event_jSlider1StateChanged
        send("Fader 1 At " + jSlider1.getValue());
    }//GEN-LAST:event_jSlider1StateChanged

    private void encoder1PlusButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encoder1PlusButtonActionPerformed
    {//GEN-HEADEREND:event_encoder1PlusButtonActionPerformed
        send("Feature $feature.1 At + 1");
    }//GEN-LAST:event_encoder1PlusButtonActionPerformed

    private void encoder1MinusButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encoder1MinusButtonActionPerformed
    {//GEN-HEADEREND:event_encoder1MinusButtonActionPerformed
        send("Feature $feature.1 At - 1");
    }//GEN-LAST:event_encoder1MinusButtonActionPerformed

    private void blackoutButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_blackoutButtonMousePressed
    {//GEN-HEADEREND:event_blackoutButtonMousePressed
        
    }//GEN-LAST:event_blackoutButtonMousePressed

    private void blackoutButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_blackoutButtonMouseReleased
    {//GEN-HEADEREND:event_blackoutButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_blackoutButtonMouseReleased

    private void blackoutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_blackoutButtonActionPerformed
    {//GEN-HEADEREND:event_blackoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blackoutButtonActionPerformed

    private void encoder2MinusButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encoder2MinusButtonActionPerformed
    {//GEN-HEADEREND:event_encoder2MinusButtonActionPerformed
        send("Feature $feature.2 At - 1");
    }//GEN-LAST:event_encoder2MinusButtonActionPerformed

    private void encoder2PlusButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encoder2PlusButtonActionPerformed
    {//GEN-HEADEREND:event_encoder2PlusButtonActionPerformed
        send("Feature $feature.2 At + 1");
    }//GEN-LAST:event_encoder2PlusButtonActionPerformed

    private void exec1ButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exec1ButtonMousePressed
    {//GEN-HEADEREND:event_exec1ButtonMousePressed
        send("ExecButton1 1");
    }//GEN-LAST:event_exec1ButtonMousePressed

    private void exec1ButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exec1ButtonMouseReleased
    {//GEN-HEADEREND:event_exec1ButtonMouseReleased
        //send("Off ExecButton1 1");
    }//GEN-LAST:event_exec1ButtonMouseReleased

    private void exec2ButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exec2ButtonMousePressed
    {//GEN-HEADEREND:event_exec2ButtonMousePressed
        send("On ExecButton2 1");
    }//GEN-LAST:event_exec2ButtonMousePressed

    private void exec2ButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exec2ButtonMouseReleased
    {//GEN-HEADEREND:event_exec2ButtonMouseReleased
        send("Off ExecButton2 1");
    }//GEN-LAST:event_exec2ButtonMouseReleased

    private void exec3ButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exec3ButtonMousePressed
    {//GEN-HEADEREND:event_exec3ButtonMousePressed
        send("On ExecButton3 1");
    }//GEN-LAST:event_exec3ButtonMousePressed

    private void exec3ButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exec3ButtonMouseReleased
    {//GEN-HEADEREND:event_exec3ButtonMouseReleased
        send("Off ExecButton3 1");
    }//GEN-LAST:event_exec3ButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blackoutButton;
    private javax.swing.JButton encoder1MinusButton;
    private javax.swing.JButton encoder1PlusButton;
    private javax.swing.JButton encoder2MinusButton;
    private javax.swing.JButton encoder2PlusButton;
    private javax.swing.JButton exec1Button;
    private javax.swing.JButton exec2Button;
    private javax.swing.JButton exec3Button;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
